WebApplication1/Models/ApplicanEx.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication1.Models
{
    public class ApplicanEx
    {
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public string Designation {  get; set; }    
        public int YearOfEx {  get; set; }
        public int AppId {  get; set; }


    }
}

WebApplication1/Models/Applicant.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace WebApplication1.Models
{
    public class Applicant
    {
       public Applicant()
        {
            ApplicanExes =new List<ApplicanEx>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        [DataType(DataType.Date)]
        public string DOB {  get; set; }
        public int TotalEx {  get; set; }
        public string PicPath {  get; set; }
        [NotMapped]
        public HttpPostedFileBase Picture { get; set; }
        public bool IsAvailable {  get; set; }
        public List<ApplicanEx> ApplicanExes { get; set; }

    }
}

WebApplication1/Models/ApplicantModel.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace WebApplication1.Models
{
    public class ApplicantModel : DbContext
    {
        public DbSet<Applicant> Applicants { get; set; }
        public DbSet<ApplicanEx>ApplicanExes { get; set; }
    }
}

WebApplication1/Controllers/ApplicantController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class ApplicantController : Controller
    {
        readonly ApplicantModel db = new ApplicantModel();
        // GET: Applicant
        public ActionResult Index()
        {
            return View(db.Applicants.ToList());
        }
        public ActionResult Create()
        {
            Applicant applicant = new Applicant();
            
            applicant.ApplicanExes.Add(new ApplicanEx
            {
                CompanyName = "",
                Designation = "",
                YearOfEx = 0
            });

            return View(applicant);
        }
        [HttpPost]
        public ActionResult Create(Applicant applicant, string btn)
        {
            if (btn == "Add")
            {
                applicant.ApplicanExes.Add(new ApplicanEx());
            }
            if (btn == "Create")
            {
                if (applicant.Picture != null)
                {
                    string ext = Path.GetExtension(applicant.Picture.FileName);
                    if (ext == ".jpg" || ext == ".png")
                    {
                        string rootpath = Server.MapPath("~/");
                        string fileTosave = Path.Combine(rootpath, "Pictures", applicant.Picture.FileName);
                        applicant.Picture.SaveAs(fileTosave);
                        applicant.PicPath = "~/Pictures/" + applicant.Picture.FileName;

                        applicant.TotalEx = applicant.ApplicanExes.Sum(s => s.YearOfEx);
                        db.Applicants.Add(applicant);
                        if (db.SaveChanges() > 0)
                        {
                            return RedirectToAction("Index");
                        }
                    }
                    else
                    {
                        ModelState.AddModelError("", "Please provide valid Image");
                        return View(applicant);
                    }
                }
                else
                {
                    ModelState.AddModelError("", "Please provide valid Image");
                    return View(applicant);
                }
            }
            return View(applicant);
        }

        public ActionResult Edit(int id)
        {
            Applicant applicant = db.Applicants.Find(id);


            return View(applicant);
        }
        [HttpPost]
        public ActionResult Edit(Applicant applicant, string btn)
        {
            var updateApp = db.Applicants.Find(applicant.Id);
            if (btn == "Add")
            {
                updateApp.ApplicanExes.Add(new ApplicanEx());
            }
            if (btn == "Update")
            {

                if (applicant.Picture != null)
                {
                    string ext = Path.GetExtension(applicant.Picture.FileName);
                    if (ext == ".jpg" || ext == ".png")
                    {
                        string rootpath = Server.MapPath("~/");
                        string fileTosave = Path.Combine(rootpath, "Pictures", applicant.Picture.FileName);
                        applicant.Picture.SaveAs(fileTosave);
                        updateApp.PicPath = "~/Pictures/" + applicant.Picture.FileName;
                    }
                    else
                    {
                        ModelState.AddModelError("", "Please provide valid Image");
                        return View(applicant);
                    }
                }
                else
                {
                    updateApp.PicPath = applicant.PicPath;
                }

                updateApp.DOB = applicant.DOB;
                updateApp.Id = applicant.Id;
                updateApp.Name = applicant.Name;
                updateApp.IsAvailable = applicant.IsAvailable;

                db.ApplicanExes.RemoveRange(db.ApplicanExes.Where(a => a.AppId.Equals(updateApp.Id)));
                db.SaveChanges();
                updateApp.ApplicanExes = applicant.ApplicanExes;
                updateApp.TotalEx = applicant.ApplicanExes.Sum(s => s.YearOfEx);
                db.Entry(updateApp).State = System.Data.Entity.EntityState.Modified;

                if (db.SaveChanges() > 0)
                {
                    return RedirectToAction("Index");
                }
            }
            return View(updateApp);
        }
        public ActionResult Delete(int id)
        {
            db.Applicants.Remove(db.Applicants.Find(id));

            db.SaveChanges();

            return RedirectToAction("Index");

        }
    }
}

WebApplication1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WebApplication1/Views/Applicant/Create.cshtml
@model WebApplication1.Models.Applicant

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Applicant", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Applicant</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DOB, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DOB, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.PicPath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                <input type="file" name="Picture" />
                @Html.ValidationMessageFor(model => model.PicPath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsAvailable, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.CheckBoxFor(model => model.IsAvailable)
                    @Html.ValidationMessageFor(model => model.IsAvailable, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add" class="btn btn-success float-end" name="btn" formnovalidate />
            </div>
        </div>
        <div class="form-group">
            <table class="table table-bordered">
                <tr>
                    <td>Company</td>
                    <td>Designation</td>
                    <td>Year of Experience</td>
                </tr>
                @for (int i = 0; i < Model.ApplicanExes.Count; i++)
                {
                    <tr>
                        <td>
                            @Html.EditorFor(m => Model.ApplicanExes[i].CompanyName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(m => Model.ApplicanExes[i].CompanyName)
                        </td>
                        <td>
                            @Html.EditorFor(m => Model.ApplicanExes[i].Designation, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(m => Model.ApplicanExes[i].Designation)
                        </td>
                        <td>
                            @Html.EditorFor(m => Model.ApplicanExes[i].YearOfEx, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(m => Model.ApplicanExes[i].YearOfEx)
                        </td>
                        <td>
                            <input type="submit" value="Remove" onclick="Remove(this)" class="btn btn-danger" />
                        </td>
                    </tr>
                }
            </table>

        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" name="btn" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        function Remove(e) {
            $(e).closest('tr').remove();
        }
    </script>
}

WebApplication1/Views/Applicant/Edit.cshtml
@model WebApplication1.Models.Applicant

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Applicant Info</h2>


@using (Html.BeginForm("Edit", "Applicant", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(m => m.Id)
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DOB, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DOB, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.PicPath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(m => m.PicPath)
                <input type="file" name="Picture" />
                @Html.ValidationMessageFor(model => model.PicPath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsAvailable, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.CheckBoxFor(model => model.IsAvailable)
                    @Html.ValidationMessageFor(model => model.IsAvailable, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add" class="btn btn-success float-end" name="btn" formnovalidate />
            </div>
        </div>
        <div class="form-group">
            <table class="table table-bordered">
                <tr>
                    <td>Company</td>
                    <td>Designation</td>
                    <td>Year of Experience</td>
                </tr>
                @for (int i = 0; i < Model.ApplicanExes.Count; i++)
                {
                    <tr>
                        <td>
                            @Html.HiddenFor(m => Model.ApplicanExes[i].AppId)
                            @Html.EditorFor(m => Model.ApplicanExes[i].CompanyName, new { htmlAttributes = new { @class = "form-control" } })

                            @Html.ValidationMessageFor(m => Model.ApplicanExes[i].CompanyName)
                        </td>
                        <td>
                            @Html.EditorFor(m => Model.ApplicanExes[i].Designation, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(m => Model.ApplicanExes[i].Designation)
                        </td>
                        <td>
                            @Html.EditorFor(m => Model.ApplicanExes[i].YearOfEx, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(m => Model.ApplicanExes[i].YearOfEx)
                        </td>
                        <td>
                            <input type="submit" value="Remove" onclick="Remove(this)" class="btn btn-danger" />
                        </td>
                    </tr>
                }
            </table>

        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Update" name="btn" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        function Remove(e) {
            $(e).closest('tr').remove();
        }
    </script>
}

WebApplication1/Views/Applicant/Index.cshtml
@model IEnumerable<WebApplication1.Models.Applicant>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DOB)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TotalEx)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PicPath)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsAvailable)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DOB)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TotalEx)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PicPath)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsAvailable)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

WebApplication1/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

WebApplication1/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

WebApplication1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Applicant", "Index", "Applicant", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>